#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_homepage:
    path: /
    controller: App\Controller\ProductosController::homepage
    methods: GET

app_iniciosesion:
    path: /usuario/login
    controller: App\Controller\UsuariosController::index
    methods: GET

app_showuser:
    path: /usuario
    controller: App\Controller\UsuariosController::show
    methods: GET


# Mario:
 #Agregar la ruta para el controlador del idioma:
app_idiomas:
    path: /idiomas/{locale}
    controller: App\Controller\IdiomasController::changeLanguage
    



    