#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_homepage:
    path: /
    controller: App\Controller\ProductosController::homepage
    methods: GET


app_iniciosesion:
    path: /usuario/login
    controller: App\Controller\UsuariosController::index
    methods: GET